# Site settings
title: Luan Nogueira Portfolio
description: Portifolio com projetos do analista de dados Luan nogueira
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
# User settings
username: Luan Nogueira
user_description: "Com anos de experiência no setor de E-commerce, Business Intelligence (BI) e vendas, estou atualmente em transição para a área de Analista de Dados. Possuo uma sólida formação acadêmica, uma certificação em Mecatrônica pelo IFSP, probabilidade e estatisca pela USP e estou atualmente realizando dois cursos na EBAC, um focado em Power BI e outro em Análise de Dados em Python. Além disso, estou cursando Engenharia de Software.<br><br>Fui honrado com o reconhecimento da Olimpíada Brasileira de Matemática em três ocasiões, destacando meu forte background quantitativo.<br><br>Possuo experiência recente com um projeto que engloba Python com utilização de bancos de dados no Google Cloud. Neste projeto, apliquei minhas habilidades em ETL, desenvolvi relatórios e modelei dados para extrair insights valiosos. A experiência adquirida em vendas e E-commerce me proporcionou uma compreensão prática das necessidades de negócios, permitindo-me enxergar como a análise de dados pode impulsionar o sucesso empresarial.<br><br>Estou ansioso para aplicar minha experiência e conhecimento em minha próxima jornada na área de Analista de Dados. Com uma base sólida em Business Intelligence e habilidades em integração de dados, estou preparado para contribuir de forma significativa em projetos de análise de dados."
user_title: Analista de Dados | BI | SQL | Python
email: luannogueiraalice@gmail.com
github_username: Luanog
linkedin_username: luan-nogueira
# Google-analytics
google-analytics:
  id: ""
exclude: ['package.json', 'src' , 'node_modules']
